# Generated by Django 6.0.1 on 2026-05-22 09:45

import django.db.models.deletion
import django.utils.timezone
import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('emoji', models.CharField(default='□', max_length=8)),
                ('color', models.CharField(default='#8b3dff', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='🏦', max_length=8)),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateField()),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ananya', max_length=80)),
                ('email', models.EmailField(default='ananya@example.com', max_length=254)),
                ('theme', models.CharField(default='dark', max_length=12)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=16)),
                ('show_currency_symbol', models.BooleanField(default=True)),
                ('expense_notifications', models.BooleanField(default=True)),
                ('weekly_summary_emails', models.BooleanField(default=False)),
                ('enable_sounds', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.DateField(default=tracker.models.current_month_start)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='tracker.category')),
            ],
            options={
                'ordering': ['category__name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Paid', 'Paid'), ('Received', 'Received'), ('Pending', 'Pending')], default='Completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='tracker.category')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
