# Generated by Django 6.0.1 on 2026-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
