# Generated by Django 6.0.1 on 2026-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_userpreference_email_alter_userpreference_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='goal_type',
            field=models.CharField(choices=[('savings', 'Savings Goal'), ('emergency', 'Emergency Fund')], default='savings', max_length=20),
        ),
    ]
