# Generated by Django 6.0.1 on 2026-06-05 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_savingsgoal_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='daily_expense_reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='daily_expense_reminder_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
    ]
